name: Pylint

on:
  workflow_call:

    
jobs:
  format:
    name: Isoort Linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install isort==5.13.2

      - name: Run isort
        run: |
          isort --profile black --check --diff .